#!/usr/bin/env python3

# obtain path to "english.wav" in the same folder as this script
from os import path

import speech_recognition as sr

AUDIO_FILE = path.join(path.dirname(path.realpath(__file__)), "out.wav")

# use the audio file as the audio source
r = sr.Recognizer()
with sr.AudioFile(AUDIO_FILE) as source:
    audio = r.record(source)  # read the entire audio file

# recognize speech using Sphinx
try:
    print(r.recognize_sphinx(audio, language="fr-FR"))
except sr.UnknownValueError:
    print("Sphinx could not understand audio")
except sr.RequestError as e:
    print("Sphinx error; {0}".format(e))
