# Step 1

MINIMAL_PHONEM_LENGTH = 0.1
MAXIMAL_MINIMAL_PHONEM_LENGH_MALUS = 1000

MAXIMAL_CONSONANT_LENGTH = 0.25
MAXIMAL_MAXIMAL_CONSONANT_LENGTH_MALUS = 1000

MAXIMAL_VOWEL_LENGTH = 0.5
MAXIMAL_MAXIMAL_VOWEL_LENGTH_MALUS = 1000

# Step 2

RATING_LENGTH_SAME_PHONEM = 80
RATING_LENGTH_SAME_WORD = 100
SCORE_SAME_TRANSCRIPTION = 200

# Step 3

RATING_SPECTRAL_SIMILARITY = 50

# Other

NODES = 1 << 12
SCORE_THRESHOLD = 50
RIGHT_PRIVILEGE = 0.8

SCORE_SAME_AUDIO_WORD = 200
MAX_DEFAULT_RATE = 500

START_MODIF = 1.0
RATE_POWER = 1.1
